id: ID22F92D5
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:18:44.559404'
last_modified: '2022-06-18T19:18:44.559417'
parser: null
source_metadata:
  title: Religious history by Nyang ral Nyima od zer (1124–1192)
  author: ཉང་རལ་ཉི་མ་འོད་ཟེར།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-11-07);
    no page numbers, unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by Tibet People's
    Publishing House (Xizang Renmin Chubanshe) (src)
  - Text input:unspecified
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2398
  bases:
    b5b5:
      title: Religious history by Nyang ral Nyima od zer (1124–1192)
      order: 1
      base_file: b5b5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
